services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # Console/UI access
      - "9001:9001"   # API access
    volumes:
      - ./minio_data:/data  # Local directory for data storage
    command: server /data --console-address ":9001"
    restart: unless-stopped


volumes:
  minio_data:
  mongodb_data: